// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type InfoReq struct {
	ID int64 `json:"id"` // 用户 ID
}

type LoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type RegisterReq struct {
	Username string `json:"username" optional: required` // 用户名
	Password string `json:"password"`                    // 密码
	Phone    string `json:"phone"`                       // 手机号
	Question string `json:"question"`                    // 找回密码问题
	Answer   string `json:"answer"`                      // 找回密码答案
}

type Response struct {
	Code    int64       `json:"code"`    // 状态码
	Message string      `json:"message"` // 返回信息
	Data    interface{} `json:"data"`    // 返回数据
}

type UserInfo struct {
	ID         int64  `json:"id"`          // 用户 ID
	Username   string `json:"username"`    // 用户名
	Phone      string `json:"phone"`       // 手机号
	CreateTime string `json:"create_time"` // 创建时间
}
