// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type AddReq struct {
	UserID   int64 `json:"userid"`   // 用户 ID
	ProID    int64 `json:"proid"`    // 商品 ID
	Quantity int64 `json:"quantity"` // 商品数量
	Checked  int64 `json:"checked"`  // 是否勾选
}

type CartItem struct {
	ID         int64  `json:"id"`          // 购物车记录 ID
	UserID     int64  `json:"userid"`      // 用户 ID
	ProID      int64  `json:"proid"`       // 商品 ID
	Quantity   int64  `json:"quantity"`    // 商品数量
	Checked    int64  `json:"checked"`     // 是否勾选
	CreateTime string `json:"create_time"` // 创建时间
	UpdateTime string `json:"update_time"` // 更新时间
}

type ListReq struct {
	UserID int64 `json:"userid"` // 用户 ID
}

type RemoveReq struct {
	ID int64 `json:"id"` // 购物车记录 ID
}

type Response struct {
	Code    int64       `json:"code"`    // 状态码
	Message string      `json:"message"` // 返回信息
	Data    interface{} `json:"data"`    // 返回数据
}

type UpdateReq struct {
	ID       int64 `json:"id"`       // 购物车记录 ID
	Quantity int64 `json:"quantity"` // 新的商品数量
}
