// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: product.proto

package product

import (
	"context"

	"go_mall/apps/product/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCategoryReq      = __.AddCategoryReq
	AddCategoryResp     = __.AddCategoryResp
	AddProductReq       = __.AddProductReq
	AddProductResp      = __.AddProductResp
	CategoryInfo        = __.CategoryInfo
	CategoryNode        = __.CategoryNode
	DeleteCategoryReq   = __.DeleteCategoryReq
	DeleteCategoryResp  = __.DeleteCategoryResp
	GetCategoryReq      = __.GetCategoryReq
	GetCategoryResp     = __.GetCategoryResp
	GetCategoryTreeReq  = __.GetCategoryTreeReq
	GetCategoryTreeResp = __.GetCategoryTreeResp
	GetProductReq       = __.GetProductReq
	GetProductResp      = __.GetProductResp
	SearchProductReq    = __.SearchProductReq
	SearchProductResp   = __.SearchProductResp
	UpdateCategoryReq   = __.UpdateCategoryReq
	UpdateCategoryResp  = __.UpdateCategoryResp
	UpdateProductReq    = __.UpdateProductReq
	UpdateProductResp   = __.UpdateProductResp

	Product interface {
		// 分类
		GetCategoryById(ctx context.Context, in *GetCategoryReq, opts ...grpc.CallOption) (*GetCategoryResp, error)
		GetCategoryTree(ctx context.Context, in *GetCategoryTreeReq, opts ...grpc.CallOption) (*GetCategoryTreeResp, error)
		AddCategory(ctx context.Context, in *AddCategoryReq, opts ...grpc.CallOption) (*AddCategoryResp, error)
		UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*UpdateCategoryResp, error)
		DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*DeleteCategoryResp, error)
		AddProduct(ctx context.Context, in *AddProductReq, opts ...grpc.CallOption) (*AddProductResp, error)
		UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error)
		GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
		SearchProduct(ctx context.Context, in *SearchProductReq, opts ...grpc.CallOption) (*SearchProductResp, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

// 分类
func (m *defaultProduct) GetCategoryById(ctx context.Context, in *GetCategoryReq, opts ...grpc.CallOption) (*GetCategoryResp, error) {
	client := __.NewProductClient(m.cli.Conn())
	return client.GetCategoryById(ctx, in, opts...)
}

func (m *defaultProduct) GetCategoryTree(ctx context.Context, in *GetCategoryTreeReq, opts ...grpc.CallOption) (*GetCategoryTreeResp, error) {
	client := __.NewProductClient(m.cli.Conn())
	return client.GetCategoryTree(ctx, in, opts...)
}

func (m *defaultProduct) AddCategory(ctx context.Context, in *AddCategoryReq, opts ...grpc.CallOption) (*AddCategoryResp, error) {
	client := __.NewProductClient(m.cli.Conn())
	return client.AddCategory(ctx, in, opts...)
}

func (m *defaultProduct) UpdateCategory(ctx context.Context, in *UpdateCategoryReq, opts ...grpc.CallOption) (*UpdateCategoryResp, error) {
	client := __.NewProductClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

func (m *defaultProduct) DeleteCategory(ctx context.Context, in *DeleteCategoryReq, opts ...grpc.CallOption) (*DeleteCategoryResp, error) {
	client := __.NewProductClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

func (m *defaultProduct) AddProduct(ctx context.Context, in *AddProductReq, opts ...grpc.CallOption) (*AddProductResp, error) {
	client := __.NewProductClient(m.cli.Conn())
	return client.AddProduct(ctx, in, opts...)
}

func (m *defaultProduct) UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error) {
	client := __.NewProductClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

func (m *defaultProduct) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	client := __.NewProductClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

func (m *defaultProduct) SearchProduct(ctx context.Context, in *SearchProductReq, opts ...grpc.CallOption) (*SearchProductResp, error) {
	client := __.NewProductClient(m.cli.Conn())
	return client.SearchProduct(ctx, in, opts...)
}
