// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type AddCategoryReq struct {
	ParentId int64  `json:"parent_id"`
	Name     string `json:"name"`
}

type CategoryNode struct {
	Id       int64          `json:"id"`
	Name     string         `json:"name"`
	Children []CategoryNode `json:"children"`
}

type DeleteCategoryReq struct {
	Id int64 `json:"id"`
}

type GetCategoryByIdReq struct {
	Id int64 `json:"id"`
}

type Response struct {
	Code    int64       `json:"code"`    // 状态码
	Message string      `json:"message"` // 返回信息
	Data    interface{} `json:"data"`    // 返回数据
}

type UpdateCategoryReq struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
