// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: cart.proto

package server

import (
	"context"

	"go_mall/apps/cart/rpc/internal/logic"
	"go_mall/apps/cart/rpc/internal/svc"
	"go_mall/apps/cart/rpc/pb"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) Add(ctx context.Context, in *__.AddReq) (*__.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *CartServer) Remove(ctx context.Context, in *__.RemoveReq) (*__.RemoveResp, error) {
	l := logic.NewRemoveLogic(ctx, s.svcCtx)
	return l.Remove(in)
}

func (s *CartServer) List(ctx context.Context, in *__.ListReq) (*__.ListResp, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *CartServer) Update(ctx context.Context, in *__.UpdateReq) (*__.UpdateResp, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}
