// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: user.proto

package server

import (
	"context"

	"go_mall/apps/user/rpc/internal/logic"
	"go_mall/apps/user/rpc/internal/svc"
	"go_mall/apps/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *__.RegisterReq) (*__.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *__.LoginReq) (*__.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Info(ctx context.Context, in *__.InfoReq) (*__.InfoResp, error) {
	l := logic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
